# AUTOGENERATED! DO NOT EDIT! File to edit: 01_eda.ipynb (unless otherwise specified).

__all__ = ['clean_genre', 'freq_words']

# Internal Cell

from sklearn.utils import shuffle
from sklearn.preprocessing import MultiLabelBinarizer
from pandas import DataFrame
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import os
import concurrent
import requests
import json

# Cell

def clean_genre(df: DataFrame) -> DataFrame:

    mlb = MultiLabelBinarizer(sparse_output=True)
    df['genres'] = [[x['name'] for x in eval(list_dict)] for list_dict in df['genres']]
    df1 = df.join(
                pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(df.pop('genres')),
                index=df.index,
                columns=mlb.classes_))
    return df1

# Cell

#Most frequent word function definition
def freq_words(df, var, num):
    from collections import Counter

    tmpStr = ""
    for i in range(len(df)):
        tmpStr = tmpStr + " " + df.iloc[i, df.columns.get_loc(var)]

    tmpList = tmpStr.lower().split()
    Counter = Counter(tmpList)
    most_freq = Counter.most_common()

    df_freq = pd.DataFrame(most_freq, columns =['Word', 'Count'])
    return df_freq.iloc[:num,:]